# StarGdalPch.cmake
#
# Reusable precompiled-header setup for the Starlight-Terrain targets.
#
# Generates a single PCH source file (gdal_pch.hpp) once into
# ${CMAKE_BINARY_DIR}/pch and attaches it to a target so that target compiles
# its OWN PCH from the shared source. Each target therefore compiles a PCH with
# its own defines -- no REUSE_FROM, no MSVC C4651/C4652 define-mismatch warnings.
#
# Usage:
#   # once, from Starlight-Terrain's CMakeLists.txt:
#   include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/StarGdalPch.cmake")
#   star_add_gdal_pch(${PROJECT_NAME})
#
#   # from any other Starlight-Terrain target added after this one:
#   if(COMMAND star_add_gdal_pch)
#       star_add_gdal_pch(<target>)
#   endif()
#
# Keep the generated contents LEAN and STABLE: every TU of a target recompiles
# whenever this content changes, and any macro that affects a header here must
# be defined identically for all callers (set such macros via
# target_compile_definitions, never per-TU #define).

include_guard(GLOBAL)

# Write a file only when its content would change, so re-running configure does
# not bump the file mtime and force a full PCH (and therefore full) rebuild.
function(star_pch_write_if_changed path content)
    if(EXISTS "${path}")
        file(SHA256 "${path}" _star_pch_old)
    else()
        set(_star_pch_old "")
    endif()
    string(SHA256 _star_pch_new "${content}")
    if(NOT _star_pch_new STREQUAL _star_pch_old)
        file(WRITE "${path}" "${content}")
    endif()
endfunction()

# Generate (idempotently) the shared GDAL PCH source and attach it to <target>.
function(star_add_gdal_pch target)
    set(STAR_PCH_DIR "${CMAKE_BINARY_DIR}/pch")

    set(_gdal_content
"// Auto-generated by CMake (extern/Starlight-Terrain/cmake/StarGdalPch.cmake). Do not edit.
#pragma once

// --- GDAL (C++ bindings) ---
#include <gdal_priv.h>
")
    star_pch_write_if_changed("${STAR_PCH_DIR}/gdal_pch.hpp" "${_gdal_content}")

    target_precompile_headers(${target} PRIVATE
        "$<$<COMPILE_LANGUAGE:CXX>:${STAR_PCH_DIR}/gdal_pch.hpp>"
    )
endfunction()
